// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/kotlin/org/intellij/sdk/language/nanomessage/lexer/NanoMessageLexer.flex

/* It's an automatically generated code. Do not modify it. */
package org.intellij.sdk.language.nanomessage.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.*;
import com.intellij.psi.xml.*;import org.intellij.sdk.language.minimessage.MiniMessageTokenType;import org.intellij.sdk.language.nanomessage.NanoMessageTokenType;


public class NanoMessageLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int START_TAG_NAME = 4;
  public static final int END_TAG_NAME = 6;
  public static final int TAG_ATTRIBUTES = 8;
  public static final int ATTRIBUTE_VALUE_START = 10;
  public static final int ATTRIBUTE_VALUE = 12;
  public static final int ATTRIBUTE_VALUE_DQ = 14;
  public static final int ATTRIBUTE_VALUE_SQ = 16;
  public static final int TAG_CHARACTERS = 18;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9, 9
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\0\2\1\22\0\1\1\1\2\1\3"+
    "\1\4\1\5\2\0\1\6\5\0\1\7\1\0\1\10"+
    "\12\11\1\12\1\0\1\13\1\0\1\14\1\15\1\0"+
    "\32\11\1\0\1\16\2\0\1\11\1\0\32\11\1\17"+
    "\1\0\1\20\7\0\1\1\44\0\1\11\12\0\1\11"+
    "\4\0\1\11\5\0\27\11\1\0\37\11\1\0\u01ca\11"+
    "\4\0\14\11\16\0\5\11\7\0\1\11\1\0\1\11"+
    "\201\0\5\11\1\0\2\11\2\0\4\11\1\0\1\11"+
    "\6\0\1\11\1\0\3\11\1\0\1\11\1\0\24\11"+
    "\1\0\123\11\1\0\213\11\10\0\246\11\1\0\46\11"+
    "\2\0\1\11\6\0\51\11\107\0\33\11\4\0\4\11"+
    "\55\0\53\11\43\0\2\11\1\0\143\11\1\0\1\11"+
    "\17\0\2\11\7\0\2\11\12\0\3\11\2\0\1\11"+
    "\20\0\1\11\1\0\36\11\35\0\131\11\13\0\1\11"+
    "\30\0\41\11\11\0\2\11\4\0\1\11\5\0\26\11"+
    "\4\0\1\11\11\0\1\11\3\0\1\11\27\0\31\11"+
    "\7\0\13\11\65\0\25\11\1\0\10\11\106\0\66\11"+
    "\3\0\1\11\22\0\1\11\7\0\12\11\17\0\20\11"+
    "\4\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\1\11\3\0\4\11\3\0\1\11\20\0\1\11"+
    "\15\0\2\11\1\0\3\11\16\0\2\11\12\0\1\11"+
    "\10\0\6\11\4\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\2\11\1\0\2\11\37\0\4\11"+
    "\1\0\1\11\23\0\3\11\20\0\11\11\1\0\3\11"+
    "\1\0\26\11\1\0\7\11\1\0\2\11\1\0\5\11"+
    "\3\0\1\11\22\0\1\11\17\0\2\11\27\0\1\11"+
    "\13\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11"+
    "\1\0\2\11\1\0\5\11\3\0\1\11\36\0\2\11"+
    "\1\0\3\11\17\0\1\11\21\0\1\11\1\0\6\11"+
    "\3\0\3\11\1\0\4\11\3\0\2\11\1\0\1\11"+
    "\1\0\2\11\3\0\2\11\3\0\3\11\3\0\14\11"+
    "\26\0\1\11\64\0\10\11\1\0\3\11\1\0\27\11"+
    "\1\0\20\11\3\0\1\11\32\0\3\11\5\0\2\11"+
    "\36\0\1\11\4\0\10\11\1\0\3\11\1\0\27\11"+
    "\1\0\12\11\1\0\5\11\3\0\1\11\40\0\1\11"+
    "\1\0\2\11\17\0\2\11\22\0\10\11\1\0\3\11"+
    "\1\0\51\11\2\0\1\11\20\0\1\11\5\0\3\11"+
    "\10\0\3\11\30\0\6\11\5\0\22\11\3\0\30\11"+
    "\1\0\11\11\1\0\1\11\2\0\7\11\72\0\60\11"+
    "\1\0\2\11\14\0\7\11\72\0\2\11\1\0\1\11"+
    "\1\0\5\11\1\0\30\11\1\0\1\11\1\0\12\11"+
    "\1\0\2\11\11\0\1\11\2\0\5\11\1\0\1\11"+
    "\25\0\4\11\40\0\1\11\77\0\10\11\1\0\44\11"+
    "\33\0\5\11\163\0\53\11\24\0\1\11\20\0\6\11"+
    "\4\0\4\11\3\0\1\11\3\0\2\11\7\0\3\11"+
    "\4\0\15\11\14\0\1\11\21\0\46\11\1\0\1\11"+
    "\5\0\1\11\2\0\53\11\1\0\115\11\1\0\4\11"+
    "\2\0\7\11\1\0\1\11\1\0\4\11\2\0\51\11"+
    "\1\0\4\11\2\0\41\11\1\0\4\11\2\0\7\11"+
    "\1\0\1\11\1\0\4\11\2\0\17\11\1\0\71\11"+
    "\1\0\4\11\2\0\103\11\45\0\20\11\20\0\126\11"+
    "\2\0\6\11\3\0\u016c\11\2\0\21\11\1\0\32\11"+
    "\5\0\113\11\6\0\10\11\7\0\15\11\1\0\4\11"+
    "\16\0\22\11\16\0\22\11\16\0\15\11\1\0\3\11"+
    "\17\0\64\11\43\0\1\11\4\0\1\11\103\0\131\11"+
    "\7\0\5\11\2\0\42\11\1\0\1\11\5\0\106\11"+
    "\12\0\37\11\61\0\36\11\2\0\5\11\13\0\54\11"+
    "\4\0\32\11\66\0\27\11\11\0\65\11\122\0\1\11"+
    "\135\0\57\11\21\0\7\11\67\0\36\11\15\0\2\11"+
    "\12\0\54\11\32\0\44\11\51\0\3\11\12\0\44\11"+
    "\2\0\11\11\7\0\53\11\2\0\3\11\51\0\4\11"+
    "\1\0\6\11\1\0\2\11\3\0\1\11\5\0\300\11"+
    "\100\0\26\11\2\0\6\11\2\0\46\11\2\0\6\11"+
    "\2\0\10\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\37\11\2\0\65\11\1\0\7\11\1\0\1\11"+
    "\3\0\3\11\1\0\7\11\3\0\4\11\2\0\6\11"+
    "\4\0\15\11\5\0\3\11\1\0\7\11\53\0\2\1"+
    "\107\0\1\11\15\0\1\11\20\0\15\11\145\0\1\11"+
    "\4\0\1\11\2\0\12\11\1\0\1\11\3\0\5\11"+
    "\6\0\1\11\1\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\13\11\2\0\4\11\5\0\5\11\4\0\1\11"+
    "\64\0\2\11\u017b\0\57\11\1\0\57\11\1\0\205\11"+
    "\6\0\4\11\3\0\2\11\14\0\46\11\1\0\1\11"+
    "\5\0\1\11\2\0\70\11\7\0\1\11\20\0\27\11"+
    "\11\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\120\0\1\11\325\0\2\11\52\0\5\11\5\0\2\11"+
    "\4\0\126\11\6\0\3\11\1\0\132\11\1\0\4\11"+
    "\5\0\53\11\1\0\136\11\21\0\33\11\65\0\306\11"+
    "\112\0\360\11\20\0\215\11\103\0\56\11\2\0\15\11"+
    "\3\0\20\11\12\0\2\11\24\0\57\11\20\0\37\11"+
    "\2\0\106\11\61\0\11\11\2\0\147\11\2\0\65\11"+
    "\2\0\5\11\60\0\13\11\1\0\3\11\1\0\4\11"+
    "\1\0\27\11\35\0\64\11\16\0\62\11\76\0\6\11"+
    "\3\0\1\11\1\0\2\11\13\0\34\11\12\0\27\11"+
    "\31\0\35\11\7\0\57\11\34\0\1\11\20\0\5\11"+
    "\1\0\12\11\12\0\5\11\1\0\51\11\27\0\3\11"+
    "\1\0\10\11\24\0\27\11\3\0\1\11\3\0\62\11"+
    "\1\0\1\11\3\0\2\11\2\0\5\11\2\0\1\11"+
    "\1\0\1\11\30\0\3\11\2\0\13\11\7\0\3\11"+
    "\14\0\6\11\2\0\6\11\2\0\6\11\11\0\7\11"+
    "\1\0\7\11\1\0\53\11\1\0\14\11\10\0\163\11"+
    "\35\0\244\11\14\0\27\11\4\0\61\11\4\0\156\11"+
    "\2\0\152\11\46\0\7\11\14\0\5\11\5\0\1\11"+
    "\1\0\12\11\1\0\15\11\1\0\5\11\1\0\1\11"+
    "\1\0\2\11\1\0\2\11\1\0\154\11\41\0\153\11"+
    "\22\0\100\11\2\0\66\11\50\0\14\11\164\0\5\11"+
    "\1\0\207\11\44\0\32\11\6\0\32\11\13\0\131\11"+
    "\3\0\6\11\2\0\6\11\2\0\6\11\2\0\3\11"+
    "\43\0\14\11\1\0\32\11\1\0\23\11\1\0\2\11"+
    "\1\0\17\11\2\0\16\11\42\0\173\11\205\0\35\11"+
    "\3\0\61\11\57\0\40\11\15\0\24\11\1\0\10\11"+
    "\6\0\46\11\12\0\36\11\2\0\44\11\4\0\10\11"+
    "\60\0\236\11\22\0\44\11\4\0\44\11\4\0\50\11"+
    "\10\0\64\11\234\0\67\11\11\0\26\11\12\0\10\11"+
    "\230\0\6\11\2\0\1\11\1\0\54\11\1\0\2\11"+
    "\3\0\1\11\2\0\27\11\12\0\27\11\11\0\37\11"+
    "\101\0\23\11\1\0\2\11\12\0\26\11\12\0\32\11"+
    "\106\0\70\11\6\0\2\11\100\0\1\11\17\0\4\11"+
    "\1\0\3\11\1\0\35\11\52\0\35\11\3\0\35\11"+
    "\43\0\10\11\1\0\34\11\33\0\66\11\12\0\26\11"+
    "\12\0\23\11\15\0\22\11\156\0\111\11\67\0\63\11"+
    "\15\0\63\11\15\0\44\11\334\0\35\11\12\0\1\11"+
    "\10\0\26\11\232\0\27\11\14\0\65\11\113\0\55\11"+
    "\40\0\31\11\32\0\44\11\35\0\1\11\13\0\43\11"+
    "\3\0\1\11\14\0\60\11\16\0\4\11\25\0\1\11"+
    "\1\0\1\11\43\0\22\11\1\0\31\11\124\0\7\11"+
    "\1\0\1\11\1\0\4\11\1\0\17\11\1\0\12\11"+
    "\7\0\57\11\46\0\10\11\2\0\2\11\2\0\26\11"+
    "\1\0\7\11\1\0\2\11\1\0\5\11\3\0\1\11"+
    "\22\0\1\11\14\0\5\11\236\0\65\11\22\0\4\11"+
    "\24\0\1\11\40\0\60\11\24\0\2\11\1\0\1\11"+
    "\270\0\57\11\51\0\4\11\44\0\60\11\24\0\1\11"+
    "\73\0\53\11\15\0\1\11\107\0\33\11\345\0\54\11"+
    "\164\0\100\11\37\0\1\11\240\0\10\11\2\0\47\11"+
    "\20\0\1\11\1\0\1\11\34\0\1\11\12\0\50\11"+
    "\7\0\1\11\25\0\1\11\13\0\56\11\23\0\1\11"+
    "\42\0\71\11\7\0\11\11\1\0\45\11\21\0\1\11"+
    "\61\0\36\11\160\0\7\11\1\0\2\11\1\0\46\11"+
    "\25\0\1\11\31\0\6\11\1\0\2\11\1\0\40\11"+
    "\16\0\1\11\u0147\0\23\11\15\0\232\11\346\0\304\11"+
    "\274\0\57\11\321\0\107\11\271\0\71\11\7\0\37\11"+
    "\161\0\36\11\22\0\60\11\20\0\4\11\37\0\25\11"+
    "\5\0\23\11\260\0\100\11\200\0\113\11\5\0\1\11"+
    "\102\0\15\11\100\0\2\11\1\0\1\11\34\0\370\11"+
    "\10\0\363\11\15\0\37\11\61\0\3\11\21\0\4\11"+
    "\10\0\u018c\11\4\0\153\11\5\0\15\11\3\0\11\11"+
    "\7\0\12\11\146\0\125\11\1\0\107\11\1\0\2\11"+
    "\2\0\1\11\2\0\2\11\2\0\4\11\1\0\14\11"+
    "\1\0\1\11\1\0\7\11\1\0\101\11\1\0\4\11"+
    "\2\0\10\11\1\0\7\11\1\0\34\11\1\0\4\11"+
    "\1\0\5\11\1\0\1\11\3\0\7\11\1\0\u0154\11"+
    "\2\0\31\11\1\0\31\11\1\0\37\11\1\0\31\11"+
    "\1\0\37\11\1\0\31\11\1\0\37\11\1\0\31\11"+
    "\1\0\37\11\1\0\31\11\1\0\10\11\64\0\55\11"+
    "\12\0\7\11\20\0\1\11\u0171\0\54\11\24\0\305\11"+
    "\73\0\104\11\7\0\1\11\264\0\4\11\1\0\33\11"+
    "\1\0\2\11\1\0\1\11\2\0\1\11\1\0\12\11"+
    "\1\0\4\11\1\0\1\11\1\0\1\11\6\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\1\11\1\0\3\11"+
    "\1\0\2\11\1\0\1\11\2\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\1\0\2\11"+
    "\1\0\1\11\2\0\4\11\1\0\7\11\1\0\4\11"+
    "\1\0\4\11\1\0\1\11\1\0\12\11\1\0\21\11"+
    "\5\0\3\11\1\0\5\11\1\0\21\11\104\0\327\11"+
    "\51\0\65\11\13\0\336\11\2\0\u0182\11\16\0\u0131\11"+
    "\37\0\36\11\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\12\0\1\1\1\2\2\1\3\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\2\5\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\16\1\21\1\22\1\23\1\22"+
    "\2\24\1\25\1\26\2\0\1\26\1\27\1\30\1\0"+
    "\1\31\1\0\1\32\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[51];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\21\0\42\0\63\0\104\0\125\0\146\0\167"+
    "\0\210\0\231\0\252\0\273\0\314\0\335\0\252\0\356"+
    "\0\377\0\252\0\252\0\u0110\0\u0121\0\252\0\252\0\u0132"+
    "\0\u0143\0\252\0\252\0\252\0\252\0\252\0\252\0\252"+
    "\0\u0143\0\252\0\252\0\252\0\u0154\0\252\0\u0143\0\u0165"+
    "\0\u0176\0\u0187\0\u0198\0\252\0\252\0\u01a9\0\u01ba\0\252"+
    "\0\u01cb\0\252\0\u01dc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[51];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\13\1\14\11\13\1\15\3\13\1\16\1\13\7\17"+
    "\1\20\3\17\1\21\1\22\4\17\1\23\1\24\1\25"+
    "\1\23\1\25\2\23\1\25\1\23\1\25\1\23\1\26"+
    "\1\23\1\25\1\23\1\27\2\23\1\24\1\25\1\23"+
    "\1\25\2\23\1\25\1\23\1\25\1\23\1\30\1\23"+
    "\1\25\4\23\1\24\6\23\1\31\1\23\1\32\1\23"+
    "\1\33\1\34\2\23\1\35\1\36\1\24\1\36\1\37"+
    "\2\36\1\40\1\36\1\41\1\36\1\32\1\36\1\33"+
    "\1\34\2\36\1\35\3\36\1\42\2\36\1\42\1\36"+
    "\1\41\1\36\1\32\1\36\1\33\1\34\2\36\1\35"+
    "\3\43\1\44\12\43\1\45\10\43\1\44\7\43\1\45"+
    "\2\43\1\46\1\24\6\46\1\47\2\46\1\26\1\33"+
    "\2\46\1\27\1\35\22\0\1\14\21\0\1\50\1\0"+
    "\1\50\2\0\1\50\1\51\1\50\3\0\1\50\5\0"+
    "\1\50\1\0\1\50\2\0\1\50\1\0\1\50\3\0"+
    "\1\50\12\0\1\52\13\0\1\53\17\0\1\24\26\0"+
    "\1\25\1\0\1\25\17\0\1\54\24\0\1\55\11\0"+
    "\1\43\22\0\1\50\1\0\1\50\11\0\1\56\1\0"+
    "\1\56\2\0\1\56\1\0\1\56\3\0\1\56\5\0"+
    "\1\57\11\0\1\60\13\0\1\61\20\0\1\56\1\0"+
    "\1\56\23\0\1\62\13\0\1\63\20\0\1\57\4\0"+
    "\1\60\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[493];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\12\0\1\11\3\1\1\11\2\1\2\11\2\1\2\11"+
    "\2\1\7\11\1\1\3\11\1\1\1\11\3\1\2\0"+
    "\2\11\1\1\1\0\1\11\1\0\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[51];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public NanoMessageLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public NanoMessageLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return XmlTokenType.XML_DATA_CHARACTERS;
            }
          // fall through
          case 27: break;
          case 2:
            { return XmlTokenType.XML_REAL_WHITE_SPACE;
            }
          // fall through
          case 28: break;
          case 3:
            { return XmlTokenType.XML_COMMENT_CHARACTERS;
            }
          // fall through
          case 29: break;
          case 4:
            { // according to HTML spec (http://www.w3.org/html/wg/drafts/html/master/syntax.html#comments)
  // comments should start with <!-- and end with -->. The comment <!--> is not valid, but should terminate
  // comment token. Please note that it's not true for XML (http://www.w3.org/TR/REC-xml/#sec-comments)
  int loc = getTokenStart();
  char prev = zzBuffer.charAt(loc - 1);
  char prevPrev = zzBuffer.charAt(loc - 2);
  if (prev == '-' && prevPrev == '-') {
    yybegin(YYINITIAL); return XmlTokenType.XML_BAD_CHARACTER;
  }
  return XmlTokenType.XML_COMMENT_CHARACTERS;
            }
          // fall through
          case 30: break;
          case 5:
            { yybegin(YYINITIAL); yypushback(1); break;
            }
          // fall through
          case 31: break;
          case 6:
            { return XmlTokenType.XML_WHITE_SPACE;
            }
          // fall through
          case 32: break;
          case 7:
            { yybegin(TAG_ATTRIBUTES); return XmlTokenType.XML_NAME;
            }
          // fall through
          case 33: break;
          case 8:
            { return XmlTokenType.XML_START_TAG_START;
            }
          // fall through
          case 34: break;
          case 9:
            { return NanoMessageTokenType.NM_PLACEHOLDER_START;
            }
          // fall through
          case 35: break;
          case 10:
            { yybegin(ATTRIBUTE_VALUE_START); return MiniMessageTokenType.MM_ATTRIBUTE_SEPARATOR;
            }
          // fall through
          case 36: break;
          case 11:
            { yybegin(YYINITIAL); return XmlTokenType.XML_TAG_END;
            }
          // fall through
          case 37: break;
          case 12:
            { yybegin(ATTRIBUTE_VALUE_START); return NanoMessageTokenType.NM_CHOICE_MARKER;
            }
          // fall through
          case 38: break;
          case 13:
            { yybegin(YYINITIAL); return NanoMessageTokenType.NM_PLACEHOLDER_END;
            }
          // fall through
          case 39: break;
          case 14:
            { yybegin(ATTRIBUTE_VALUE); return XmlTokenType.XML_ATTRIBUTE_VALUE_TOKEN;
            }
          // fall through
          case 40: break;
          case 15:
            { yybegin(ATTRIBUTE_VALUE_DQ); return XmlTokenType.XML_ATTRIBUTE_VALUE_START_DELIMITER;
            }
          // fall through
          case 41: break;
          case 16:
            { yybegin(ATTRIBUTE_VALUE_SQ); return XmlTokenType.XML_ATTRIBUTE_VALUE_START_DELIMITER;
            }
          // fall through
          case 42: break;
          case 17:
            { return XmlTokenType.XML_BAD_CHARACTER;
            }
          // fall through
          case 43: break;
          case 18:
            { return XmlTokenType.XML_ATTRIBUTE_VALUE_TOKEN;
            }
          // fall through
          case 44: break;
          case 19:
            { yybegin(TAG_ATTRIBUTES); return XmlTokenType.XML_ATTRIBUTE_VALUE_END_DELIMITER;
            }
          // fall through
          case 45: break;
          case 20:
            { return XmlTokenType.XML_TAG_CHARACTERS;
            }
          // fall through
          case 46: break;
          case 21:
            { yybegin(START_TAG_NAME); yypushback(yylength());
            }
          // fall through
          case 47: break;
          case 22:
            { return XmlTokenType.XML_END_TAG_START;
            }
          // fall through
          case 48: break;
          case 23:
            { yybegin(YYINITIAL); return XmlTokenType.XML_EMPTY_ELEMENT_END;
            }
          // fall through
          case 49: break;
          case 24:
            { yybegin(END_TAG_NAME); yypushback(yylength());
            }
          // fall through
          case 50: break;
          case 25:
            { yybegin(YYINITIAL); return XmlTokenType.XML_COMMENT_END;
            }
          // fall through
          case 51: break;
          case 26:
            { yybegin(YYINITIAL); return XmlTokenType.XML_BAD_CHARACTER;
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
