{
  parserClass="org.intellij.sdk.language.parser.AmpersandParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ampersand"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.sdk.language.psi"
  psiImplPackage="org.intellij.sdk.language.psi.impl"

  elementTypeHolderClass="org.intellij.sdk.language.psi.AmpersandTypes"
  elementTypeClass="org.intellij.sdk.language.psi.AmpersandElementType"
  tokenTypeClass="org.intellij.sdk.language.psi.AmpersandTokenType"
}

document ::= content+ <<eof>>
private content ::= formatter | text
formatter ::= SYMBOL format
format ::= color_format | hexcolor_format | deco_format | special_format
color_format ::= COLOR
hexcolor_format ::= HEXCOLOR
deco_format ::= DECO
special_format ::= SPECIAL
text ::= MISC | ESCAPE | format | SYMBOL