{
    tokens=[
        whitespace="regexp:\s+"
        bopen="("
        bclose=")"
        boolop="regexp:and|or"
        bool="regexp:true|false"
    ]
}


document ::= content <<eof>>

content ::= element

element ::= brackets | operation | value

brackets ::= bopen element bclose {extends=element}
operation ::= element whitespace boolop whitespace element {extends=element}
value ::= bool {extends=element}
private recover ::= !bclose